### ISSUE TITLE
Test with Github actions

### ISSUE THREAD

**Issue by laulaz** [collective/collective.autoscaling#6]
```
Traceback (most recent call last):
  File "/home/travis/build/collective/collective.autoscaling/bin/flake8", line 24, in <module>
    sys.exit(flake8.main.main())
  File "/home/travis/build/collective/collective.autoscaling/buildout-cache/eggs/flake8-2.5.4-py2.7.egg/flake8/main.py", line 25, in main
    flake8_style = get_style_guide(parse_argv=True, config_file=DEFAULT_CONFIG)
  File "/home/travis/build/collective/collective.autoscaling/buildout-cache/eggs/flake8-2.5.4-py2.7.egg/flake8/engine.py", line 233, in get_style_guide
    kwargs['parser'], options_hooks = get_parser()
  File "/home/travis/build/collective/collective.autoscaling/buildout-cache/eggs/flake8-2.5.4-py2.7.egg/flake8/engine.py", line 95, in get_parser
    parser_hook(parser)
  File "/home/travis/build/collective/collective.autoscaling/buildout-cache/eggs/flake8_coding-1.3.1-py2.7.egg/flake8_coding.py", line 23, in add_options
    help="Warn for files containing a `coding:` magic comment"
  File "/opt/python/2.7.14/lib/python2.7/optparse.py", line 1013, in add_option
    option = self.option_class(*args, **kwargs)
  File "/opt/python/2.7.14/lib/python2.7/optparse.py", line 570, in __init__
    self._set_attrs(attrs)
  File "/opt/python/2.7.14/lib/python2.7/optparse.py", line 625, in _set_attrs
    self)
optparse.OptionError: option --no-accept-encodings: invalid keyword arguments: parse_from_config
```

```
AssertionError: Setup failed:
WebDriverException: Message: Can't load the profile. Profile Dir: %s If you specified a log_file in the FirefoxBinary constructor, check it for details.
```

**Comment by laulaz** [comment]
Travis is dead for OSS project ... we should use Github Actions now !

**Comment by laulaz** [comment]
Done, but robots tests are missing for now ...

**Comment by laulaz** [comment]
Robots tests are now added 👍
